FROM node:14.15.4-slim
LABEL maintainer="shirakiya"

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY .eslintrc.json .
COPY index.tmpl.html .
COPY static ./static
COPY webpack.*.js ./
COPY src ./src

CMD ["npm", "start"]
