version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: syakusyaku-frontend
    container_name: syakusyaku-frontend
    environment:
      - GOOGLE_API_KEY
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    command: npm start
