npm:
  restore_cache: &npm_restore_cache
    keys:
      - npm-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - npm-v1-{{ .Branch }}-
      - npm-v1-

  install: &npm_install
    name: Install npm modules
    command: npm install

  save_cache: &npm_save_cache
    key: npm-v1-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ./node_modules

version: 2.1
executors:
  nodejs:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/syakusyaku
jobs:
  lint:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          <<: *npm_restore_cache
      - run:
          <<: *npm_install
      - save_cache:
          <<: *npm_save_cache
      - run:
          name: Check Lint
          command: npm run lint

  build:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          <<: *npm_restore_cache
      - run:
          <<: *npm_install
      - save_cache:
          <<: *npm_save_cache
      - run:
          name: Build webpack
          command: npm run build:prd
      - persist_to_workspace:
          root: public
          paths:
            - "*"

  deploy-firebase:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: public
      - run:
          name: Install firebase-cli
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting --project $CIRCLE_PROJECT_REPONAME --token $FIREBASE_TOKEN --message $CIRCLE_TAG

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy-firebase:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
