npm:
  restore_cache: &npm_restore_cache
    keys:
      - npm-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - npm-v1-{{ .Branch }}-
      - npm-v1-

  install: &npm_install
    name: Install npm modules
    command: npm install

  save_cache: &npm_save_cache
    key: npm-v1-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ./node_modules

version: 2.1
orbs:
  terraform: circleci/terraform@1.2.0
executors:
  nodejs:
    docker:
      - image: circleci/node:14.15.4
    working_directory: ~/syakusyaku
jobs:
  lint:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          <<: *npm_restore_cache
      - run:
          <<: *npm_install
      - save_cache:
          <<: *npm_save_cache
      - run:
          name: Check Lint
          command: npm run lint

workflows:
  version: 2
  test:
    jobs:
      - lint
      - terraform/fmt:
          checkout: true
          path: terraform/
      - terraform/validate:
          checkout: true
          backend: false
          path: terraform/
