version: 2.1

orbs:
  node: circleci/node@5.2.0

executors:
  nodejs:
    docker:
      - image: cimg/node:22.3.0
    working_directory: ~/syakusyaku

jobs:
  lint:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          pkg-manager: npm
      - run:
          name: Check Lint
          command: npm run lint

  prettier:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          pkg-manager: npm
      - run:
          name: Check Lint
          command: npm run prettier:check

  build:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          cache-version: v1
          pkg-manager: npm
      - run:
          name: Build webpack
          command: npm run build:prd
      - store_artifacts:
          path: public
      - persist_to_workspace:
          root: public
          paths:
            - '*'

  deploy-firebase:
    executor: nodejs
    steps:
      - checkout
      - attach_workspace:
          at: public
      - run:
          name: Install firebase-cli
          command: sudo npm install -g firebase-tools
      - run:
          name: Deploy to Firebase Hosting
          command: firebase deploy --only hosting --project $CIRCLE_PROJECT_REPONAME --token $FIREBASE_TOKEN --message $CIRCLE_TAG

workflows:
  test-and-deploy:
    jobs:
      - lint:
          filters:
            tags:
              only: /^v.*/
      - prettier:
          filters:
            tags:
              only: /^v.*/
      - build:
          requires:
            - lint
            - prettier
          filters:
            tags:
              only: /^v.*/
      - deploy-firebase:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
